In [1]:
import pandas as pd

In [2]:
MontrealOriginal = pd.read_csv('Montreal.csv')
MontrealOriginal.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2078,Central comfy close to Metro Laurie,2277,Nelia,NaN,Le Plateau-Mont-Royal,45.53069,-73.58588,Private room,38,2,245,2018-09-23,2.13,1,42
1,29059,Lovely studio Quartier Latin,125031,Maryline,NaN,Ville-Marie,45.51939,-73.56482,Entire home/apt,133,2,330,2020-10-27,2.54,2,343
2,29061,Maison historique - Quartier Latin,125031,Maryline,NaN,Ville-Marie,45.51929,-73.56493,Entire home/apt,252,3,69,2020-11-01,0.63,2,352
3,31847,Downtown/Airport room,2319,Gail,NaN,Le Sud-Ouest,45.48467,-73.57995,Private room,40,2,153,2020-01-07,1.18,5,318
4,34715,Chez Patrac ! Métro Beaubien,149769,Alain,NaN,Rosemont-La Petite-Patrie,45.53840,-73.60355,Entire home/apt,135,4,4,2011-09-12,0.03,1,358

In [3]:
MontrealOriginal.rename(columns = {
    'host_name':'Host Name',
    'neighbourhood': 'Neighbourhood',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'room_type': 'Room Type',
    'price': 'Price',
    'minimum_nights': 'Minimum Nights',
    'availability_365': 'Availability 365'}, inplace = True)
MontrealOriginal.head()

,id,name,host_id,Host Name,neighbourhood_group,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,Availability 365
0,2078,Central comfy close to Metro Laurie,2277,Nelia,NaN,Le Plateau-Mont-Royal,45.53069,-73.58588,Private room,38,2,245,2018-09-23,2.13,1,42
1,29059,Lovely studio Quartier Latin,125031,Maryline,NaN,Ville-Marie,45.51939,-73.56482,Entire home/apt,133,2,330,2020-10-27,2.54,2,343
2,29061,Maison historique - Quartier Latin,125031,Maryline,NaN,Ville-Marie,45.51929,-73.56493,Entire home/apt,252,3,69,2020-11-01,0.63,2,352
3,31847,Downtown/Airport room,2319,Gail,NaN,Le Sud-Ouest,45.48467,-73.57995,Private room,40,2,153,2020-01-07,1.18,5,318
4,34715,Chez Patrac ! Métro Beaubien,149769,Alain,NaN,Rosemont-La Petite-Patrie,45.53840,-73.60355,Entire home/apt,135,4,4,2011-09-12,0.03,1,358

In [4]:
Montreal = MontrealOriginal[['Host Name','Neighbourhood','Latitude','Longitude','Room Type','Price','Minimum Nights','Availability 365']]
Montreal.head()

,Host Name,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,Availability 365
0,Nelia,Le Plateau-Mont-Royal,45.53069,-73.58588,Private room,38,2,42
1,Maryline,Ville-Marie,45.51939,-73.56482,Entire home/apt,133,2,343
2,Maryline,Ville-Marie,45.51929,-73.56493,Entire home/apt,252,3,352
3,Gail,Le Sud-Ouest,45.48467,-73.57995,Private room,40,2,318
4,Alain,Rosemont-La Petite-Patrie,45.53840,-73.60355,Entire home/apt,135,4,358

In [5]:
NewBrunswickOriginal = pd.read_csv('New Brunswick.csv')
NewBrunswickOriginal.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,75065,Bay cottage on Passamaquoddy bay,397069,Bob,Charlotte,Saint Andrews,45.13241,-67.04725,Entire home/apt,243,2,18,2020-08-23,0.26,1,196
1,145013,Lobster Lane Cottage: private beach,642972,Jennifer,Kent,Dundas,46.32857,-64.52445,Entire home/apt,125,7,8,2020-08-23,0.10,1,227
2,261800,Furnished Executive Close to City,1373498,Usha,Saint John,City of Saint John,45.27727,-66.06040,Entire home/apt,100,2,44,2020-10-03,0.77,2,364
3,791070,Private room in a friendly home!,72953,Stephen,Westmorland,Sackville,45.89572,-64.37684,Private room,69,1,50,2019-12-15,0.54,1,363
4,872640,Acadian Isle Retreat - Heron Haven,2189998,Danielle,Gloucester,Shippagan,47.86785,-64.52187,Entire home/apt,135,7,3,2019-08-18,0.03,1,365

In [6]:
NewBrunswickOriginal.rename(columns = {
    'host_name':'Host Name',
    'neighbourhood': 'Neighbourhood',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'room_type': 'Room Type',
    'price': 'Price',
    'minimum_nights': 'Minimum Nights',
    'availability_365': 'Availability 365'}, inplace = True)
NewBrunswickOriginal.head()

,id,name,host_id,Host Name,neighbourhood_group,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,Availability 365
0,75065,Bay cottage on Passamaquoddy bay,397069,Bob,Charlotte,Saint Andrews,45.13241,-67.04725,Entire home/apt,243,2,18,2020-08-23,0.26,1,196
1,145013,Lobster Lane Cottage: private beach,642972,Jennifer,Kent,Dundas,46.32857,-64.52445,Entire home/apt,125,7,8,2020-08-23,0.10,1,227
2,261800,Furnished Executive Close to City,1373498,Usha,Saint John,City of Saint John,45.27727,-66.06040,Entire home/apt,100,2,44,2020-10-03,0.77,2,364
3,791070,Private room in a friendly home!,72953,Stephen,Westmorland,Sackville,45.89572,-64.37684,Private room,69,1,50,2019-12-15,0.54,1,363
4,872640,Acadian Isle Retreat - Heron Haven,2189998,Danielle,Gloucester,Shippagan,47.86785,-64.52187,Entire home/apt,135,7,3,2019-08-18,0.03,1,365

In [7]:
NewBrunswick = NewBrunswickOriginal[['Host Name','Neighbourhood','Latitude','Longitude','Room Type','Price','Minimum Nights','Availability 365']]
NewBrunswick.head()

,Host Name,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,Availability 365
0,Bob,Saint Andrews,45.13241,-67.04725,Entire home/apt,243,2,196
1,Jennifer,Dundas,46.32857,-64.52445,Entire home/apt,125,7,227
2,Usha,City of Saint John,45.27727,-66.06040,Entire home/apt,100,2,364
3,Stephen,Sackville,45.89572,-64.37684,Private room,69,1,363
4,Danielle,Shippagan,47.86785,-64.52187,Entire home/apt,135,7,365

In [8]:
OttawaOriginal = pd.read_csv('Ottawa.csv')
OttawaOriginal.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,34220,Room available,147438,Mark,NaN,Capital,45.40924,-75.67900,Private room,202,7,0,NaN,NaN,1,0
1,36642,City Conveniences A Country Setting,157787,Donna,NaN,Kitchissippi,45.40159,-75.74679,Private room,65,3,87,2020-02-17,0.67,1,288
2,59258,Lower level of my house to rent,284351,Elena,NaN,Bay,45.35900,-75.80314,Entire home/apt,200,3,1,2011-07-04,0.01,1,0
3,158824,DOWNTOWN/GLEBE HOUSE WITH BACKYARD,87296,Luc,NaN,Capital,45.40248,-75.69941,Entire home/apt,140,3,7,2015-08-30,0.06,1,12
4,261065,Westboro Village Executive Suite,1369632,Glenn,NaN,Kitchissippi,45.38972,-75.75496,Entire home/apt,150,3,64,2020-10-19,0.57,1,281

In [9]:
OttawaOriginal.rename(columns = {
    'host_name':'Host Name',
    'neighbourhood': 'Neighbourhood',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'room_type': 'Room Type',
    'price': 'Price',
    'minimum_nights': 'Minimum Nights',
    'availability_365': 'Availability 365'}, inplace = True)
OttawaOriginal.head()

,id,name,host_id,Host Name,neighbourhood_group,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,Availability 365
0,34220,Room available,147438,Mark,NaN,Capital,45.40924,-75.67900,Private room,202,7,0,NaN,NaN,1,0
1,36642,City Conveniences A Country Setting,157787,Donna,NaN,Kitchissippi,45.40159,-75.74679,Private room,65,3,87,2020-02-17,0.67,1,288
2,59258,Lower level of my house to rent,284351,Elena,NaN,Bay,45.35900,-75.80314,Entire home/apt,200,3,1,2011-07-04,0.01,1,0
3,158824,DOWNTOWN/GLEBE HOUSE WITH BACKYARD,87296,Luc,NaN,Capital,45.40248,-75.69941,Entire home/apt,140,3,7,2015-08-30,0.06,1,12
4,261065,Westboro Village Executive Suite,1369632,Glenn,NaN,Kitchissippi,45.38972,-75.75496,Entire home/apt,150,3,64,2020-10-19,0.57,1,281

In [10]:
Ottawa = OttawaOriginal[['Host Name','Neighbourhood','Latitude','Longitude','Room Type','Price','Minimum Nights','Availability 365']]
Ottawa.head()

,Host Name,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,Availability 365
0,Mark,Capital,45.40924,-75.67900,Private room,202,7,0
1,Donna,Kitchissippi,45.40159,-75.74679,Private room,65,3,288
2,Elena,Bay,45.35900,-75.80314,Entire home/apt,200,3,0
3,Luc,Capital,45.40248,-75.69941,Entire home/apt,140,3,12
4,Glenn,Kitchissippi,45.38972,-75.75496,Entire home/apt,150,3,281

In [11]:
QuebecCityOriginal = pd.read_csv('Quebec City.csv')
QuebecCityOriginal.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,54334,Beau logement avec vue magnifique sur les mont...,254811,Charlotte,NaN,Quartier 5-1,46.91400,-71.19565,Entire home/apt,100,2,93,2020-08-28,0.80,1,357
1,138381,Bed & Breakfast La California,675584,Mary,NaN,Sillery,46.76843,-71.26636,Private room,145,1,147,2019-12-15,1.25,3,364
2,198548,Fabulous view in heart of Québec,960772,Marianne,NaN,Saint-Roch,46.81233,-71.22545,Entire home/apt,150,30,49,2020-12-21,0.43,1,346
3,214967,Au bord du fleuve,1110010,Julie,NaN,Vieux-Québec/Cap-Blanc/Colline parlementaire,46.80286,-71.21271,Private room,83,2,162,2020-09-08,1.57,1,364
4,268812,Apartment Old city Quebec condo,1408583,Émilie,NaN,Vieux-Québec/Cap-Blanc/Colline parlementaire,46.81023,-71.21082,Entire home/apt,40,30,77,2019-02-07,0.69,1,311

In [12]:
QuebecCityOriginal.rename(columns = {
    'host_name':'Host Name',
    'neighbourhood': 'Neighbourhood',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'room_type': 'Room Type',
    'price': 'Price',
    'minimum_nights': 'Minimum Nights',
    'availability_365': 'Availability 365'}, inplace = True)
QuebecCityOriginal.head()

,id,name,host_id,Host Name,neighbourhood_group,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,Availability 365
0,54334,Beau logement avec vue magnifique sur les mont...,254811,Charlotte,NaN,Quartier 5-1,46.91400,-71.19565,Entire home/apt,100,2,93,2020-08-28,0.80,1,357
1,138381,Bed & Breakfast La California,675584,Mary,NaN,Sillery,46.76843,-71.26636,Private room,145,1,147,2019-12-15,1.25,3,364
2,198548,Fabulous view in heart of Québec,960772,Marianne,NaN,Saint-Roch,46.81233,-71.22545,Entire home/apt,150,30,49,2020-12-21,0.43,1,346
3,214967,Au bord du fleuve,1110010,Julie,NaN,Vieux-Québec/Cap-Blanc/Colline parlementaire,46.80286,-71.21271,Private room,83,2,162,2020-09-08,1.57,1,364
4,268812,Apartment Old city Quebec condo,1408583,Émilie,NaN,Vieux-Québec/Cap-Blanc/Colline parlementaire,46.81023,-71.21082,Entire home/apt,40,30,77,2019-02-07,0.69,1,311

In [13]:
QuebecCity = QuebecCityOriginal[['Host Name','Neighbourhood','Latitude','Longitude','Room Type','Price','Minimum Nights','Availability 365']]
QuebecCity.head()

,Host Name,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,Availability 365
0,Charlotte,Quartier 5-1,46.91400,-71.19565,Entire home/apt,100,2,357
1,Mary,Sillery,46.76843,-71.26636,Private room,145,1,364
2,Marianne,Saint-Roch,46.81233,-71.22545,Entire home/apt,150,30,346
3,Julie,Vieux-Québec/Cap-Blanc/Colline parlementaire,46.80286,-71.21271,Private room,83,2,364
4,Émilie,Vieux-Québec/Cap-Blanc/Colline parlementaire,46.81023,-71.21082,Entire home/apt,40,30,311

In [14]:
TorontoOriginal = pd.read_csv('Toronto.csv')
TorontoOriginal.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,1419,Beautiful home in amazing area!,1565,Alexandra,NaN,Little Portugal,43.64617,-79.42451,Entire home/apt,469,28,7,2017-12-04,0.10,1,0
1,8077,Downtown Harbourfront Private Room,22795,Kathie & Larry,NaN,Waterfront Communities-The Island,43.64105,-79.37628,Private room,96,180,169,2013-08-27,1.21,2,365
2,23691,Queen Bedroom close to downtown,93825,Yohan & Sarah,NaN,Briar Hill-Belgravia,43.69602,-79.45468,Private room,72,28,217,2019-12-22,1.66,2,362
3,27423,Executive Studio Unit- Ideal for One Person,118124,Brent,NaN,Greenwood-Coxwell,43.66890,-79.32592,Entire home/apt,45,365,26,2011-08-30,0.20,1,346
4,30931,Downtown Toronto - Waterview Condo,22795,Kathie & Larry,NaN,Waterfront Communities-The Island,43.64151,-79.37643,Entire home/apt,128,180,1,2010-08-11,0.01,2,365

In [15]:
TorontoOriginal.rename(columns = {
    'host_name':'Host Name',
    'neighbourhood': 'Neighbourhood',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'room_type': 'Room Type',
    'price': 'Price',
    'minimum_nights': 'Minimum Nights',
    'availability_365': 'Availability 365'}, inplace = True)
TorontoOriginal.head()

,id,name,host_id,Host Name,neighbourhood_group,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,Availability 365
0,1419,Beautiful home in amazing area!,1565,Alexandra,NaN,Little Portugal,43.64617,-79.42451,Entire home/apt,469,28,7,2017-12-04,0.10,1,0
1,8077,Downtown Harbourfront Private Room,22795,Kathie & Larry,NaN,Waterfront Communities-The Island,43.64105,-79.37628,Private room,96,180,169,2013-08-27,1.21,2,365
2,23691,Queen Bedroom close to downtown,93825,Yohan & Sarah,NaN,Briar Hill-Belgravia,43.69602,-79.45468,Private room,72,28,217,2019-12-22,1.66,2,362
3,27423,Executive Studio Unit- Ideal for One Person,118124,Brent,NaN,Greenwood-Coxwell,43.66890,-79.32592,Entire home/apt,45,365,26,2011-08-30,0.20,1,346
4,30931,Downtown Toronto - Waterview Condo,22795,Kathie & Larry,NaN,Waterfront Communities-The Island,43.64151,-79.37643,Entire home/apt,128,180,1,2010-08-11,0.01,2,365

In [16]:
Toronto = TorontoOriginal[['Host Name','Neighbourhood','Latitude','Longitude','Room Type','Price','Minimum Nights','Availability 365']]
Toronto.head()

,Host Name,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,Availability 365
0,Alexandra,Little Portugal,43.64617,-79.42451,Entire home/apt,469,28,0
1,Kathie & Larry,Waterfront Communities-The Island,43.64105,-79.37628,Private room,96,180,365
2,Yohan & Sarah,Briar Hill-Belgravia,43.69602,-79.45468,Private room,72,28,362
3,Brent,Greenwood-Coxwell,43.66890,-79.32592,Entire home/apt,45,365,346
4,Kathie & Larry,Waterfront Communities-The Island,43.64151,-79.37643,Entire home/apt,128,180,365

In [17]:
VancouverOriginal = pd.read_csv('Vancouver.csv')
VancouverOriginal.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,10080,D1 - Million Dollar View 2 BR,30899,Rami,NaN,Downtown,49.28772,-123.12279,Entire home/apt,150,90,16,2017-02-26,0.14,41,345
1,13358,Monthly (or Longer ) Designer One Bedroom Down...,52116,Lynn,NaN,West End,49.28209,-123.12515,Entire home/apt,90,30,430,2021-01-01,3.32,1,70
2,13490,Vancouver's best kept secret,52467,Iris,NaN,Kensington-Cedar Cottage,49.25622,-123.06607,Entire home/apt,145,30,88,2020-10-31,0.75,1,291
3,14267,EcoLoft Vancouver,56030,Peter & Alison,NaN,Kensington-Cedar Cottage,49.24974,-123.08108,Entire home/apt,199,3,33,2020-02-07,0.26,1,0
4,16254,Close to PNE/Hastings Park and East Village,63238,Jason,NaN,Hastings-Sunrise,49.27734,-123.04152,Entire home/apt,195,3,5,2019-08-19,0.16,1,228

In [18]:
VancouverOriginal.rename(columns = {
    'host_name':'Host Name',
    'neighbourhood': 'Neighbourhood',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'room_type': 'Room Type',
    'price': 'Price',
    'minimum_nights': 'Minimum Nights',
    'availability_365': 'Availability 365'}, inplace = True)
VancouverOriginal.head()

,id,name,host_id,Host Name,neighbourhood_group,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,Availability 365
0,10080,D1 - Million Dollar View 2 BR,30899,Rami,NaN,Downtown,49.28772,-123.12279,Entire home/apt,150,90,16,2017-02-26,0.14,41,345
1,13358,Monthly (or Longer ) Designer One Bedroom Down...,52116,Lynn,NaN,West End,49.28209,-123.12515,Entire home/apt,90,30,430,2021-01-01,3.32,1,70
2,13490,Vancouver's best kept secret,52467,Iris,NaN,Kensington-Cedar Cottage,49.25622,-123.06607,Entire home/apt,145,30,88,2020-10-31,0.75,1,291
3,14267,EcoLoft Vancouver,56030,Peter & Alison,NaN,Kensington-Cedar Cottage,49.24974,-123.08108,Entire home/apt,199,3,33,2020-02-07,0.26,1,0
4,16254,Close to PNE/Hastings Park and East Village,63238,Jason,NaN,Hastings-Sunrise,49.27734,-123.04152,Entire home/apt,195,3,5,2019-08-19,0.16,1,228

In [19]:
Vancouver = VancouverOriginal[['Host Name','Neighbourhood','Latitude','Longitude','Room Type','Price','Minimum Nights','Availability 365']]
Vancouver.head()

,Host Name,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,Availability 365
0,Rami,Downtown,49.28772,-123.12279,Entire home/apt,150,90,345
1,Lynn,West End,49.28209,-123.12515,Entire home/apt,90,30,70
2,Iris,Kensington-Cedar Cottage,49.25622,-123.06607,Entire home/apt,145,30,291
3,Peter & Alison,Kensington-Cedar Cottage,49.24974,-123.08108,Entire home/apt,199,3,0
4,Jason,Hastings-Sunrise,49.27734,-123.04152,Entire home/apt,195,3,228

In [20]:
CanadianAirbnb = pd.concat([Montreal, NewBrunswick, Ottawa, QuebecCity, Toronto, Vancouver])
CanadianAirbnb.head(20)

,Host Name,Neighbourhood,Latitude,Longitude,Room Type,Price,Minimum Nights,Availability 365
0,Nelia,Le Plateau-Mont-Royal,45.53069,-73.58588,Private room,38,2,42
1,Maryline,Ville-Marie,45.51939,-73.56482,Entire home/apt,133,2,343
2,Maryline,Ville-Marie,45.51929,-73.56493,Entire home/apt,252,3,352
3,Gail,Le Sud-Ouest,45.48467,-73.57995,Private room,40,2,318
4,Alain,Rosemont-La Petite-Patrie,45.53840,-73.60355,Entire home/apt,135,4,358
5,Sylvie,Le Plateau-Mont-Royal,45.52836,-73.58342,Entire home/apt,130,3,319
6,M.,Ville-Marie,45.52699,-73.55840,Private room,50,10,365
7,Zhang,Mercier-Hochelaga-Maisonneuve,45.54571,-73.53853,Entire home/apt,37,360,365
8,Maureen,Côte-des-Neiges-Notre-Dame-de-Grâce,45.46834,-73.60695,Entire home/apt,80,3,365
9,Noémie,Rosemont-La Petite-Patrie,45.54157,-73.60737,Entire home/apt,65,3,37
10,Antoine,Le Plateau-Mont-Royal,45.52908,-73.57499,Entire home/apt,100,7,38
11,Chris,Le Plateau-Mont-Royal,45.51979,-73.57737,Entire home/apt,206,5,0
12,Kimberley,Dorval,45.44239,-73.76493,Private room,53,1,365
13,Seb,Ville-Marie,45.50584,-73.55602,Entire home/apt,90,3,0
14,Dan,Montréal-Ouest,45.45372,-73.65060,Private room,150,3,0
15,Zhang,Mercier-Hochelaga-Maisonneuve,45.54628,-73.53676,Entire home/apt,28,700,365
16,Zhang,Mercier-Hochelaga-Maisonneuve,45.54620,-73.53660,Entire home/apt,33,1000,365
17,Jennifer&Steeve,Le Sud-Ouest,45.47816,-73.55510,Entire home/apt,185,3,238
18,Sylvie,Le Plateau-Mont-Royal,45.52975,-73.58401,Entire home/apt,110,30,339
19,Dan & Chris,Côte-des-Neiges-Notre-Dame-de-Grâce,45.46444,-73.62603,Entire home/apt,185,9,44

In [21]:
CanadianAirbnb.to_csv('CanadianCityAirbnb.csv')